### ISSUE TITLE
No branches on the code spaces repo

### ISSUE THREAD

**Issue by jasojone** [LinkedInLearning/hands-on-javascript-2499547#3]
## Issue Overview

Your course is asking for branch checkouts, and there is only one branch currently. I see the file structure is named for each chapter. So it is deviating a bit. I will continue with the course to see if there are any further issues. 
## Describe your environment

Codespaces https://github.com/LinkedInLearning/hands-on-javascript-2499547/codespaces
## Steps to Reproduce

1.
2.
3.
4.

## Expected Behavior

There to be branches
## Current Behavior

No branches. 
## Possible Solution

Update the video to reflect repo changes.

**Comment by jasojone** [comment]
I believe that this is not an issue, and you were just explaining the functionality

**Comment by planetoftheweb** [comment]
try doing a git pull --all in the terminal. In a newer version of this project, I added that command so it should be automatically performing it on startup now. Try creating a new codespace.
